FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_API_BASE=.
ENV VITE_API_BASE=$VITE_API_BASE
ARG VITE_DSLAB_URL=/ds-lab/
ENV VITE_DSLAB_URL=$VITE_DSLAB_URL
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
