import {useEffect,useState} from 'react';
import {apiUrl} from '../config/api';
import {categoryFor} from '../config/rawIndicatorTotals';
export default function MapIndicatorControls({value,onChange,metric,period,onPeriodChange}){
 const [indicators,setIndicators]=useState([]),[category,setCategory]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();fetch(apiUrl('/api/municipalities/metadata'),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Indicator catalogue unavailable');return r.json();}).then(b=>{const rows=(b.data?.indicators || []).filter(r=>!r.isProxy&&(r.rawMunicipalities == null ? r.periods?.length>0 : r.rawMunicipalities>0)&&!/index|composite|0.?100/i.test(r.unit || ''));setIndicators(rows);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[]);
 const categories=[...new Set(indicators.map(categoryFor))].sort();
 const selected=indicators.find(r=>`indicator:${r.key}`===value);
 const active=category || (selected?categoryFor(selected):categories.includes('Crime')?'Crime':categories[0]);
 const options=indicators.filter(r=>categoryFor(r)===active);
 return <div className="profiler-mapControls"><div className="profiler-controlHeading"><span>EXPLORE THE DATA</span><h2>Compare municipalities</h2><p>Select a category and an indicator to colour the map.</p></div><label>Category<select value={active || ''} onChange={e=>{setCategory(e.target.value);const row=indicators.find(r=>categoryFor(r)===e.target.value && r.key==='crime_murder') || indicators.find(r=>categoryFor(r)===e.target.value);if(row)onChange(`indicator:${row.key}`);}}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Map indicator<select value={selected&&categoryFor(selected)===active?value:''} onChange={e=>onChange(e.target.value)}><option value="">Choose a raw-value indicator</option>{options.map(r=><option key={r.key} value={`indicator:${r.key}`}>{r.label} · {r.unit}</option>)}</select></label>{selected&&<label>Year / period<select value={period || ''} onChange={e=>onPeriodChange(e.target.value)}><option value="">Latest available</option>{[...(selected.periods || [])].reverse().map(year=><option key={year} value={year}>{year}</option>)}</select></label>}<p>Only layers with available raw values are listed.</p>{selected&&<section className="profiler-layerSource" aria-label="Layer source"><div><span className="profiler-layerSource__eyebrow">DATA SOURCE</span><strong>{selected.sourceName || 'Source not supplied'}</strong><span>{metric?.key===selected.key ? metric.period || 'Period not supplied' : 'Loading displayed period…'} · {selected.unit}</span></div><details><summary>Layer metadata</summary><p>{selected.description || 'Description not supplied.'}</p><dl><dt>Available periods</dt><dd>{selected.periods?.join(', ') || 'Not supplied'}</dd><dt>Scenario</dt><dd>{metric?.key===selected.key ? metric.scenario || 'Not supplied' : 'Loading…'}</dd><dt>Local record updated</dt><dd>{selected.updatedAt ? new Date(selected.updatedAt).toLocaleDateString('en-ZA') : 'Not supplied'}</dd></dl>{selected.sourceUrl&&<a href={selected.sourceUrl} target="_blank" rel="noreferrer">Open original source ↗</a>}</details></section>}{error&&<p role="alert">{error}</p>}</div>;
}
