import {useEffect,useState} from 'react';
import {apiUrl} from '../config/api';
export default function MunicipalComparison({indicators,municipality,onSelect}){
 const [key,setKey]=useState(''),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[samePeriod,setSamePeriod]=useState(true);
 const chosen=indicators.find(r=>r.key===key) || indicators[0];
 const chosenKey=chosen?.key;
 useEffect(()=>{if(!chosenKey)return;const c=new AbortController();let active=true;
 const request=async()=>{try{const r=await fetch(apiUrl(`/api/municipalities/metric?metric=${encodeURIComponent(`indicator:${chosenKey}`)}`),{signal:c.signal});if(!r.ok)throw Error('Could not load comparison');const b=await r.json();if(active){setRows(b.data.records);setError('');}}catch(e){if(active&&e.name!=='AbortError')setError(e.message);}finally{if(active)setLoading(false);}};
 queueMicrotask(()=>{if(active){setLoading(true);request();}});return()=>{active=false;c.abort();};},[chosenKey]);
 if(!chosen)return <p>No raw indicators in this category are available for comparison.</p>;
 const compatible=r=>r.period===chosen.period && (r.scenario || '')===(chosen.scenario || '') && r.displayUnit===(chosen.displayUnit || chosen.unit) && r.sourceName===chosen.sourceName;
 const visible=rows.filter(r=>r.rawValue!=null && !r.isProxy && r.confidence!=='proxy' && (!samePeriod||compatible(r)) && r.municipality.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b.rawValue)-Number(a.rawValue));
 function exportCsv(){const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=[['Municipality','Indicator','Raw value','Unit','Period','Scenario','Source'],...visible.map(r=>[r.municipality,chosen.label,r.rawValue,r.displayUnit,r.period,r.scenario,r.sourceName])].map(row=>row.map(q).join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='municipal-comparison.csv';a.click();URL.revokeObjectURL(u);}
 return <section className="municipal-compare"><h3>Compare municipalities</h3><div className="municipal-compare__controls"><label>Indicator<select value={chosen.key} onChange={e=>setKey(e.target.value)}>{indicators.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></label><label>Find municipalities<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter by municipality name"/></label></div><label><input type="checkbox" checked={samePeriod} onChange={e=>setSamePeriod(e.target.checked)}/> Match the selected municipality’s unit, source, period and scenario</label><p>Comparing {chosen.label} · {chosen.period || 'Unknown period'} · {chosen.displayUnit || chosen.unit}. Raw counts are not population-adjusted rates or risk rankings.</p>{loading&&<p role="status">Loading comparisons…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&<><p>{visible.length} municipalities with usable source values. Missing data is not zero.</p><button disabled={!visible.length} onClick={exportCsv}>Download comparison CSV</button><div className="raw-municipal__table"><table><thead><tr><th>Municipality</th><th>Raw value</th><th>Period / scenario</th><th>Source</th></tr></thead><tbody>{visible.map(r=><tr key={r.gid} className={r.gid===municipality.gid?'is-selected':''}><th scope="row"><button onClick={()=>onSelect(r.gid)}>{r.municipality}{r.gid===municipality.gid?' · selected':''}</button></th><td><strong>{Number(r.rawValue).toLocaleString('en-ZA',{maximumFractionDigits:3})}</strong><small>{r.displayUnit}</small></td><td>{r.period || 'Unknown'}<small>{r.scenario}</small>{!compatible(r)&&<small>Different comparison basis</small>}</td><td>{r.sourceName || 'Unknown'}</td></tr>)}</tbody></table></div></> }</section>;
}
