import { isExpiredForecast } from "../config/forecastFreshness";
import "../styles/municipal-evidence-summary.css";
const format = (v, unit = "") => v == null || !Number.isFinite(Number(v)) ? "Not available" : `${Number(v).toLocaleString("en-ZA", {maximumFractionDigits: 1})} ${unit}`.trim();
export default function MunicipalEvidenceSummary({profile, onSection}) {
    const records = profile.indicators?.records || [];
    const evidence = records.filter(r => !r.isProxy && r.confidence !== "proxy");
    const pressures = evidence.filter(r => r.direction !== "context" && r.adjustedValue != null && !/raw count|\bcases\b|composite score/i.test(r.displayUnit || r.unit || "")).sort((a,b) => b.adjustedValue-a.adjustedValue).filter((r,i,rows) => rows.findIndex(other => other.theme === r.theme) === i).slice(0,3);
    const domains = (profile.indicators?.indices || []).filter(r => !/composite|overall|combined/i.test(r.key));
    const f = profile.forecast || {};
    const end = f.forecastEnd ? String(f.forecastEnd).slice(0,10) : null;
    const periods = [...new Set(evidence.map(r => r.period).filter(Boolean))];
    return <section className="sarva-evidence" aria-label="Municipal planning evidence">
        <header><small>PLANNING EVIDENCE</small><h3>What the available data can tell us</h3><p>Municipal indicators describe relative pressures. Weather forecasts describe short-term hazards. Neither establishes who or what will be harmed.</p></header>
        <div className="sarva-evidence__quality"><strong>{evidence.length} non-placeholder indicators · {records.length-evidence.length} proxy placeholders</strong><p>Source periods: {periods.join(", ") || "not recorded"}. Coverage is not scientific confidence. Imported values have not been independently validated here.</p><button onClick={() => onSection("indicators")}>Inspect sources and gaps</button></div>
        <h4>Municipal pressures to investigate</h4>
        {pressures.length ? <ul>{pressures.map(r => <li key={r.key}><strong>{r.label}</strong><span>{r.rawValue != null ? format(r.rawValue,r.displayUnit) : "Raw source value unavailable"}</span><small>Relative pressure {format(r.adjustedValue)} / 100 · {r.period || "Period unknown"} · {r.sourceName || "Source unknown"}</small></li>)}</ul> : <p>No non-placeholder pressure indicators available. This does not mean low risk.</p>}
        <p>These are the highest available comparison scores, limited to one per theme, not proven causes of impacts. Raw crime counts and precomputed sub-indices are excluded from this list; counts need suitable denominators and sub-indices need documented methods. Separately normalized periods should not be read as trends.</p>
        <details><summary>Domain comparisons and evidence coverage</summary><p>Legacy indices average available weighted inputs. Missing inputs change the effective weights. Compare only matching periods, scenarios and inputs. Scores are not probabilities of harm.</p>{domains.map(r => <article key={r.key}><strong>{r.label}</strong><p>{format(r.score)} / 100 · {r.indicatorCount} of {r.expectedIndicatorCount} inputs ({format(r.coveragePercent,"%")})</p><small>Count coverage only; weighted coverage and validation unavailable. Legacy indices may include placeholders.</small></article>)}{!domains.length && <p>No domain comparisons available.</p>}</details>
        <h4>Short-term weather screening</h4><div className="sarva-evidence__quality"><strong>{isExpiredForecast(end) ? "Expired forecast — historical context only" : end && f.latestRun?.finishedAt ? "Cached forecast — verify against official updates" : "Forecast currency cannot be established"}</strong><p>Window: {f.forecastStart ? String(f.forecastStart).slice(0,10) : "unknown"} to {end || "unknown"}. {f.pointCount || 0} forecast points/records intersect the municipality.</p></div>
        <div className="sarva-evidence__hazards">{[["Rainfall",f.maxRainfallMm,"mm/day"],["Heat",f.maxTemperatureC,"°C"],["Wind",f.maxWindKmh,"km/h"]].map(([label,value,unit]) => <article key={label}><small>{label}</small><strong>{format(value,unit)}</strong><p>Maximum within the municipality and forecast window.</p></article>)}</div>
        <p>Rainfall is not a flood assessment. Fire weather is a heat, wind and dryness proxy, not measured fire occurrence. Coarse forecast fields do not identify exposed homes, roads or facilities.</p>
        <h4>What to do next</h4><ol><li>Check source dates, missing inputs and proxy status before using comparisons.</li><li>Review local records for the pressures above with the responsible municipal service team.</li><li>Establish hazard-specific exposure using settlements, assets and hazard footprints before prioritising interventions. Exposure and expected losses are not calculated here.</li><li>Use nearby observations as supporting context; proximity alone does not establish representativeness.</li></ol><button onClick={() => onSection("observations")}>Explore supporting observations</button>
        <details><summary>Assessment method and limits</summary><p>Hazards are kept separate from vulnerability and capacity indicators. No new risk model or validated weights are introduced. Placeholders are excluded from the pressure list; missing values remain unknown. Boundaries, resolution and source periods must align before combining evidence.</p><a href="https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-1/" target="_blank" rel="noreferrer">IPCC framework: hazard, exposure, vulnerability and responses</a></details>
    </section>;
}
